### ISSUE TITLE
Using locally hosted version of drawio

### ISSUE THREAD

**Issue by subhanshu-shukla-ril** [marcveens/react-drawio#54]
Hi Team,
When I am using this plugin with locally hosted version of drawio, I am getting below error

<img width="1718" alt="Image" src="https://github.com/user-attachments/assets/608f5d3f-6616-4ad0-abc1-eb47db7db8f2" />

Here is my docker compose of locally hosted drawio

```yaml
version: '3'

services:
  drawio:
    image: tomcat:9-jdk11
    container_name: drawio-server
    ports:
      - '28080:8080'
    volumes:
      - ./.local/draw.war:/usr/local/tomcat/webapps/drawio.war
    environment:
      - TZ=UTC
```
My component

```tsx
 <DrawIoEmbed
          key="draw-view"
          baseUrl="http://localhost:28080/drawio/"
          urlParameters={{
            lightbox: true,
          }}
          xml={xml}
        />
```

Local drawio installation working fine

<img width="1721" alt="Image" src="https://github.com/user-attachments/assets/35fc239b-1582-4809-8d8f-8ff611bf5370" />
